# https://docs.github.com/en/actions/using-workflows/about-workflows

name: Code Check

on:
  pull_request:
    branches: ["master"]

env:
  SKIP_ENV_VALIDATION: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3.0

      # ? https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.12

      - name: Setup node
        uses: actions/setup-node@3.0
        with:
          version: 18
          cache: "pnpm"

      # Hopefully this caches stuff

      - name: Install deps (with cache)
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run typecheck
        run: pnpm run typecheck
